# Generated by Django 5.2.13 on 2026-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
